server:
  port: 8083

spring:
  application:
    name: student-management-system-staging

  datasource:
    url: jdbc:h2:mem:stagingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
    com.sridhar.springboot: INFO